# Service for thndr-api application
apiVersion: v1
kind: Service
metadata:
  name: thndr-api-service
  namespace: thndr-app
  labels:
    app: thndr-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: thndr-api
