apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thndr-api-ingress
  namespace: thndr-app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: thndr-api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: thndr-api-service
                port:
                  number: 80
